### ISSUE TITLE
'Apr 12, 2021' could not be parsed at index 0: DateTime parse Exception

### ISSUE THREAD

**Issue by kkuez** [devcsrj/mvnrepository-client#2]
To parse correctly, you need to apply a locale to the DateTimeFormatter.
I took ENGLISH for mvnrepository. 
Should be a quick fix in devcsrj/mvnrepository/ArtifactSearchEntriesPage#61:
`
LocalDate.parse(date, DateTimeFormatter.ofPattern("MMM d, uuuu", Locale.ENGLISH))
`

**Comment by devcsrj** [comment]
Oh, thanks for spotting this! Would love to review a PR from you! :)

**Comment by kkuez** [comment]
There you go, check you inbox :)
I'm glad you're still interested in this really useful lib and replied to fast and would kindly ask you for a new release, as I would love to use this in a companies project.

**Comment by devcsrj** [comment]
Fixed by #3
